-- Añadir columna companyId donde falta
ALTER TABLE payments ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE production_batches ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE production_batch_items ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE vehicle_loading_items ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE route_settlements ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE route_settlement_items ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE recurring_orders ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE recurring_order_items ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE commissions ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE commission_items ADD COLUMN IF NOT EXISTS company_id INTEGER NOT NULL DEFAULT 1;